name: CD - Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  push_commit:
    name: Push commit
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only run for merged PRs
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Init git config
        run: |
          git config user.email "support+actions@github.com"
          git config user.name "github-actions-bot"

      - name: Create and push commit
        run: |
          git commit -m "Dummy commit" --allow-empty
          git push origin

  deploy_production:
    name: Deploy Production
    needs: push_commit
    uses: ./.github/workflows/deploy_to_env.yml
    with:
      ref: main
