name: Fetch PR head SHA
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

jobs:
  get_pr_head_sha:
    name: Get PR head SHA
    runs-on: ubuntu-latest
    if: |
      contains(github.event.review.body, 'deploy to stage please') ||
      (contains(github.event.comment.body, 'deploy to stage please') && github.event.issue.pull_request)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get and write PR data to output
        id: pr_data
        run: |
          PR_DATA=$(gh pr view "$PR_NUMBER" --json headRefOid,number)
          echo "NUMBER=$(echo $PR_DATA | jq .number)" >> "$GITHUB_OUTPUT"
          echo "HEAD_REF=$(echo $PR_DATA | jq .headRefOid)" >> "$GITHUB_OUTPUT"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Print PR number
        run: echo ${{ steps.pr_data.outputs.NUMBER }}

      - name: Print PR head ref
        run: echo ${{ steps.pr_data.outputs.HEAD_REF }}
