name: PR comment
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

jobs:
  create_new_comment:
    name: Create new comment
    runs-on: ubuntu-latest
    if: |
      contains(github.event.review.body, 'create new comment') ||
      (contains(github.event.comment.body, 'create new comment') && github.event.issue.pull_request)

    steps:
      - uses: dannyskoog/pr-commenter-action@main
        with:
          message: Create new comment

  update_existing_comment:
    name: Update existing comment
    runs-on: ubuntu-latest
    if: |
      contains(github.event.review.body, 'update comment') ||
      (contains(github.event.comment.body, 'update comment') && github.event.issue.pull_request)

    steps:
      - uses: dannyskoog/pr-commenter-action@main
        with:
          message: Update existing comment. 1st comment
          marker: <!-- my-marker -->

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - uses: dannyskoog/pr-commenter-action@main
        with:
          message: Update existing comment. 2nd comment
          marker: <!-- my-marker -->
