name: PR comment
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    outputs:
      preview_channel: ${{ steps.preview_channel.outputs.preview_channel }}

    if: |
      contains(github.event.review.body, 'deploy to dev please') ||
      (contains(github.event.comment.body, 'deploy to dev please') && github.event.issue.pull_request)

    steps:
      - uses: dannyskoog/pr-commenter-action@main
        with:
          message: This is my cool comment!
